<div id="Login-Window">

  <h1>Please Login</h1>

  <form action="login/authorize" method="post">

    <div class="form-group">
      <label>Username</label>
      <input type="text" name="usrnm">
    </div>

    <div class="form-group">
      <label>Password</label>
      <input type="password" name="pswd">
    </div>

    <div class="form-group">
      <input type="submit" value="Login"
    </div>

  </form>

</div>
